In [ ]:
# prompt: import numpy as np
# import pandas as pd
# # Read csv file to create dataframe
# retaildf1 = pd.read_csv("/content/retail_sales.csv")
# print(retaildf1)
# retaildf1.info()
# retaildf1.describe()
# # To Find Duplicates
# duplicates = retaildf[retaildf1.duplicated()]
# print(duplicates)
# dropdupdf = retaildf1.drop_duplicates()
# print(dropdupdf)
# dropdupdf.isnull().sum()
# # Handling missing values
# # using mean of to place missing values as it is a numerical data based on Category
# dropdupdf['Price'] = dropdupdf['Price'].fillna(dropdupdf.groupby("Category")['Price'].transform('mean'))
# print(dropdupdf)
# # to Convert date format to YYYY-MM-DD
# dropdupdf['Date'] = pd.to_datetime(dropdupdf['Date'],format = '%m/%d/%y').dt.strftime('%Y-%m-%d')
# print(dropdupdf)
# # Filter Data with only first word in category column
# dropdupdf['Category'] = dropdupdf['Category'].str.split().str[0]
# print(dropdupdf['Category'])
# # Categorize products based on price
# dropdupdf['Price_Category'] = dropdupdf['Price'].apply(lambda x: 'Expensive' if x > 500 else 'Affordable')
# print(dropdupdf)
# import numpy as np
# import pandas as pd

# Assuming 'retaildf' is defined and contains the data
# ... (Your existing code) ...

# To Find Duplicates
duplicates = retaildf1[retaildf1.duplicated()]
print("Duplicates:")
print(duplicates)

# Drop duplicates
dropdupdf = retaildf1.drop_duplicates()
print("\nDataFrame after dropping duplicates:")
print(dropdupdf)

# Check for null values
print("\nNull values count per column:")
print(dropdupdf.isnull().sum())

# Handling missing values (using mean of 'Price' grouped by 'Category')
dropdupdf['Price'] = dropdupdf['Price'].fillna(dropdupdf.groupby("Category")['Price'].transform('mean'))
print("\nDataFrame after handling missing 'Price' values:")
print(dropdupdf)

# Convert 'Date' format to YYYY-MM-DD
dropdupdf['Date'] = pd.to_datetime(dropdupdf['Date'], format='%m/%d/%y').dt.strftime('%Y-%m-%d')
print("\nDataFrame after converting 'Date' format:")
print(dropdupdf)

# Filter data with only the first word in 'Category' column
dropdupdf['Category'] = dropdupdf['Category'].str.split().str[0]
print("\n'Category' column after extracting the first word:")
print(dropdupdf['Category'])

# Categorize products based on price
dropdupdf['Price_Category'] = dropdupdf['Price'].apply(lambda x: 'Expensive' if x > 500 else 'Affordable')
print("\nDataFrame after adding 'Price_Category':")
dropdupdf

# ... (Rest of your code) ...

NameError: name 'retaildf1' is not defined

In [ ]:
!pip install pandas sqlalchemy psycopg2-binary requests

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.39)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.11/dist-packages (2.9.10)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [47]:
import pandas as pd
import numpy as np

In [48]:
import pandas as pd

retaildf = pd.read_csv('/retail_sales.csv')
display(retaildf.head())

   Order_id Product_name         Category   Price        Date   Source
0       101       Laptop      Electronics  1201.0     12/5/23   Amazon
1       102        Phone      Electronics   800.0  13/05/2023     ebay
2       103        Shoes  Fashion Apparel    50.5  14/05/2023   Amazon
3       104        Phone      Electronics     NaN  15/05/2023  walmart
4       105        Shirt  Fashion Apparel    30.0  16/05/2023     ebay

In [49]:
retaildf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_id      6 non-null      int64
 1   Product_name  6 non-null      object
 2   Category      6 non-null      object
 3   Price         5 non-null      float64
 4   Date          6 non-null      object
 5   Source        6 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 420.0+ bytes

In [50]:
retaildf.describe()

         Order_id        Price
count    6.000000     5.000000
mean   102.833333   576.300000
std      1.471960   516.053001
min    101.000000    30.000000
25%    102.000000    50.500000
50%    102.500000   800.000000
75%    103.750000   800.000000
max    105.000000  1201.000000

In [51]:
# To Find Duplicates
duplicates = retaildf[retaildf.duplicated()]
print(duplicates)

   Order_id Product_name     Category  Price        Date Source
5       102        Phone  Electronics  800.0  13/05/2023   ebay

In [52]:
dropdupdf = retaildf.drop_duplicates()
print(dropdupdf)

   Order_id Product_name         Category   Price        Date   Source
0       101       Laptop      Electronics  1201.0     12/5/23   Amazon
1       102        Phone      Electronics   800.0  13/05/2023     ebay
2       103        Shoes  Fashion Apparel    50.5  14/05/2023   Amazon
3       104        Phone      Electronics     NaN  15/05/2023  walmart
4       105        Shirt  Fashion Apparel    30.0  16/05/2023     ebay

In [53]:
dropdupdf.isnull().sum()

Order_id        0
Product_name    0
Category        0
Price           1
Date            0
Source          0
dtype: int64

In [54]:
# Handling missing values
# using mean of to place missing values as it is a numerical data based on Category
dropdupdf['Price'] = dropdupdf['Price'].fillna(dropdupdf.groupby("Category")['Price'].transform('mean'))
print(dropdupdf)

   Order_id Product_name         Category   Price        Date   Source
0       101       Laptop      Electronics  1201.0     12/5/23   Amazon
1       102        Phone      Electronics   800.0  13/05/2023     ebay
2       103        Shoes  Fashion Apparel    50.5  14/05/2023   Amazon
3       104        Phone      Electronics  1000.5  15/05/2023  walmart
4       105        Shirt  Fashion Apparel    30.0  16/05/2023     ebay

<ipython-input-54-b7633aea13d8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropdupdf['Price'] = dropdupdf['Price'].fillna(dropdupdf.groupby("Category")['Price'].transform('mean'))

In [55]:
dropdupdf['Date'] = pd.to_datetime(dropdupdf['Date'], dayfirst=True).dt.strftime('%Y-%m-%d')
print(dropdupdf)

   Order_id Product_name         Category   Price        Date   Source
0       101       Laptop      Electronics  1201.0  2023-05-12   Amazon
1       102        Phone      Electronics   800.0  2023-05-13     ebay
2       103        Shoes  Fashion Apparel    50.5  2023-05-14   Amazon
3       104        Phone      Electronics  1000.5  2023-05-15  walmart
4       105        Shirt  Fashion Apparel    30.0  2023-05-16     ebay

<ipython-input-55-c799e07e6102>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dropdupdf['Date'] = pd.to_datetime(dropdupdf['Date'], dayfirst=True).dt.strftime('%Y-%m-%d')
<ipython-input-55-c799e07e6102>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropdupdf['Date'] = pd.to_datetime(dropdupdf['Date'], dayfirst=True).dt.strftime('%Y-%m-%d')

In [57]:
# Filter Data with only first word in category column
dropdupdf['Category'] = dropdupdf['Category'].str.split().str[0]
print(dropdupdf['Category'])

0    Electronics
1    Electronics
2        Fashion
3    Electronics
4        Fashion
Name: Category, dtype: object

<ipython-input-57-ff14b4d34e68>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropdupdf['Category'] = dropdupdf['Category'].str.split().str[0]

In [58]:
# Categorize products based on price
dropdupdf['Price_Category'] = dropdupdf['Price'].apply(lambda x: 'Expensive' if x > 500 else 'Affordable')

print(dropdupdf)

   Order_id Product_name     Category   Price        Date   Source  \
0       101       Laptop  Electronics  1201.0  2023-05-12   Amazon
1       102        Phone  Electronics   800.0  2023-05-13     ebay
2       103        Shoes      Fashion    50.5  2023-05-14   Amazon
3       104        Phone  Electronics  1000.5  2023-05-15  walmart
4       105        Shirt      Fashion    30.0  2023-05-16     ebay

  Price_Category
0      Expensive
1      Expensive
2     Affordable
3      Expensive
4     Affordable

<ipython-input-58-0e01d658c278>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropdupdf['Price_Category'] = dropdupdf['Price'].apply(lambda x: 'Expensive' if x > 500 else 'Affordable')